[package]
name = "blarg"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/sawatzkylindsey/blarg"
keywords = ["argument", "cli", "arg", "parser", "parse"]
categories = ["command-line-interface"]
description = "A type-safe, domain sensitive, argument-option paradigm command line parser."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0"
rand = "^0.8"

[dev-dependencies]
empty = "0.0.4"
rstest = "^0.12"
assert_matches = "1.5"
