[package]
name = "blarg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0"
rand = "^0.8"

[dev-dependencies]
empty = "0.0.4"
rstest = "^0.12"
