[package]
name = "blarg_derive"
license.workspace = true
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.62"
quote = "1.0.28"
syn = { version = "2.0.28", features = ["full"] }
